### ISSUE TITLE
Asking to update Google Play Services 

### ISSUE THREAD

**Issue by AllwinJohnson** [myinnos/Google-Code-Scanner#2]
Exception: Code scanner module is not supported on current Google Play Services version, please upgrade.

full crash log 

` Error
                                                 com.google.mlkit.common.MlKitException: Code scanner module is not supported on current Google Play Services version, please upgrade.
                                                 	at com.google.mlkit.vision.codescanner.internal.zze.startScan(com.google.android.gms:play-services-code-scanner@@16.0.0:8)
                                                 	at com.omang.app.utils.ScannerManager.startScan(ScannerManager.kt:52)
                                                 	at com.omang.app.ui.registration.fragments.RegistrationFragment$scanCode$1.invokeSuspend(RegistrationFragment.kt:115)
                                                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
                                                 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
                                                 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
                                                 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
                                                 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
                                                 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
                                                 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
                                                 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
                                                 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
                                                 	at com.omang.app.ui.registration.fragments.RegistrationFragment.scanCode(RegistrationFragment.kt:114)
                                                 	at com.omang.app.ui.registration.fragments.RegistrationFragment.bindView$lambda$10$lambda$6(RegistrationFragment.kt:81)
                                                 	at com.omang.app.ui.registration.fragments.RegistrationFragment.$r8$lambda$CJ4pvVUKqirsR2_emQLScpVpJbU(Unknown Source:0)
                                                 	at com.omang.app.ui.registration.fragments.RegistrationFragment$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
                                                 	at android.view.View.performClick(View.java:7147)
                                                 	at android.view.View.performClickInternal(View.java:7120)
                                                 	at android.view.View.access$3500(View.java:804)
                                                 	at android.view.View$PerformClick.run(View.java:27538)
                                                 	at android.os.Handler.handleCallback(Handler.java:883)
                                                 	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                 	at android.os.Looper.loop(Looper.java:214)
                                                 	at android.app.ActivityThread.main(ActivityThread.java:7405)
                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
                                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)`

**Comment by kartikchhipa** [comment]
I am also facing the same issue unable to figure out the solution
